# Assignment-15- Random Forests- Fraud check

In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Import Dataset
fc = pd.read_csv('Fraud_check.csv')
fc

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [4]:
fc.loc[fc['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
fc.loc[fc['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [8]:
fc.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good  
2   YES           Good  
3   YES           Good  
4    NO           Good

In [11]:
fc.drop('Taxable.Income',1,inplace=True)

C:\Users\swara\AppData\Local\Temp\ipykernel_10264\4219745728.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  fc.drop('Taxable.Income',1,inplace=True)


KeyError: "['Taxable.Income'] not found in axis"

In [12]:
fc.head()

Undergrad Marital.Status  City.Population  Work.Experience Urban  \
0        NO         Single            50047               10   YES   
1       YES       Divorced           134075               18   YES   
2        NO        Married           160205               30   YES   
3       YES         Single           193264               15   YES   
4        NO        Married            27533               28    NO   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [13]:
fc['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [14]:
from sklearn import preprocessing

In [15]:
lable_encoder = preprocessing.LabelEncoder()
fc['Marital.Status'] = lable_encoder.fit_transform(fc['Marital.Status'])
fc['Marital.Status'].unique()

array([2, 0, 1])

In [16]:
fc.head()

Undergrad  Marital.Status  City.Population  Work.Experience Urban  \
0        NO               2            50047               10   YES   
1       YES               0           134075               18   YES   
2        NO               1           160205               30   YES   
3       YES               2           193264               15   YES   
4        NO               1            27533               28    NO   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [17]:
fc.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [18]:
fc['Undergrad'] = lable_encoder.fit_transform(fc['Undergrad'])
fc['Undergrad'].unique()

array([0, 1])

In [19]:
fc.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [20]:
fc['Urban'] = lable_encoder.fit_transform(fc['Urban'])
fc['Urban'].unique()

array([1, 0])

In [21]:
fc.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [22]:
colnames = list(fc.columns)
predictors = colnames[0:5]
target = colnames[5]

In [23]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [24]:
target

'Taxable_Income'

In [25]:
x = fc[predictors]
y = fc[target]

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(x,y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [29]:
fc.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [30]:
fc['rf_pred'] =rf.predict(x)

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
confusion_matrix(fc['Taxable_Income'],fc['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)